# actionbarから
execute as @s[scores={PreviewRole=1}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §4人狼§r"}]}
execute as @s[scores={PreviewRole=2}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §5狂人§r"}]}
execute as @s[scores={PreviewRole=3}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §b預言者§r"}]}
execute as @s[scores={PreviewRole=4}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §e霊媒師§r"}]}
execute as @s[scores={PreviewRole=5}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §a村人§r"}]}
execute as @s[scores={PreviewRole=6}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §b怪盗§r"}]}
execute as @s[scores={PreviewRole=7}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §g猫又§r"}]}
execute as @s[scores={PreviewRole=8}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §e狐§r"}]}
execute as @s[scores={PreviewRole=9}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §7狂信者§r"}]}
execute as @s[scores={PreviewRole=10}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §4大狼§r"}]}
execute as @s[scores={PreviewRole=11}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §4賢狼§r"}]}
execute as @s[scores={PreviewRole=12}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §6パン屋§r"}]}
execute as @s[scores={PreviewRole=13}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §7囁く狂人§r"}]}
execute as @s[scores={PreviewRole=14}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §a村人§r"}]}
execute as @s[scores={PreviewRole=15}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §d女王§r"}]}
execute as @s[scores={PreviewRole=16}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §dプリンセス§r"}]}
execute as @s[scores={PreviewRole=17}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §a狩人§r"}]}
execute as @s[scores={PreviewRole=18}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §7ボマー§r"}]}
execute as @s[scores={PreviewRole=21}] run titleraw @s actionbar {"rawtext":[{"text":"あなたの役職: §bカウンセラー§r"}]}