execute as @s[scores={CurrentRole=1}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7人狼が死亡しました"}]}
execute as @s[scores={CurrentRole=2}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7狂人が死亡しました"}]}
execute as @s[scores={CurrentRole=3}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7預言者が死亡しました"}]}
execute as @s[scores={CurrentRole=4}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7霊媒師が死亡しました"}]}
execute as @s[scores={CurrentRole=5}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7村人が死亡しました"}]}
execute as @s[scores={CurrentRole=6}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7怪盗が死亡しました"}]}
execute as @s[scores={CurrentRole=7}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7猫又が死亡しました"}]}
execute as @s[scores={CurrentRole=8}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7狐が死亡しました"}]}
execute as @s[scores={CurrentRole=9}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7狂信者が死亡しました"}]}
execute as @s[scores={CurrentRole=10}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7大狼が死亡しました"}]}
execute as @s[scores={CurrentRole=11}] run tellraw @a[scores={CurrentRole=11,a_live=1}] {"rawtext":[{"text":"§7賢狼が死亡しました"}]}
