scoreboard players set @p[scores={give_item=0}] give_item 1
scoreboard players set @p[scores={give_item=0}] give_item 2
scoreboard players set @p[scores={give_item=0}] give_item 3
scoreboard players set @p[scores={give_item=0}] give_item 4
scoreboard players set @p[scores={give_item=0}] give_item 5
scoreboard players set @p[scores={give_item=0}] give_item 6
scoreboard players set @p[scores={give_item=0}] give_item 7
scoreboard players set @p[scores={give_item=0}] give_item 8
scoreboard players set @p[scores={give_item=0}] give_item 9
scoreboard players set @p[scores={give_item=0}] give_item 10
scoreboard players set @p[scores={give_item=0}] give_item 11
scoreboard players set @p[scores={give_item=0}] give_item 12
scoreboard players set @p[scores={give_item=0}] give_item 13
scoreboard players set @p[scores={give_item=0}] give_item 14
scoreboard players set @p[scores={give_item=0}] give_item 15
scoreboard players set @p[scores={give_item=0}] give_item 16
scoreboard players set @p[scores={give_item=0}] give_item 17
scoreboard players set @p[scores={give_item=0}] give_item 18
scoreboard players set @p[scores={give_item=0}] give_item 19
scoreboard players set @p[scores={give_item=0}] give_item 20
scoreboard players set @p[scores={give_item=0}] give_item 21
scoreboard players set @p[scores={give_item=0}] give_item 22
scoreboard players set @p[scores={give_item=0}] give_item 23
scoreboard players set @p[scores={give_item=0}] give_item 24
scoreboard players set @p[scores={give_item=0}] give_item 25
scoreboard players set @p[scores={give_item=0}] give_item 26
scoreboard players set @p[scores={give_item=0}] give_item 27
scoreboard players set @p[scores={give_item=0}] give_item 28
scoreboard players set @p[scores={give_item=0}] give_item 29
scoreboard players set @p[scores={give_item=0}] give_item 30