execute as @s[scores={CurrentRole=1}] run scoreboard players add 人狼 StartRoll 1
execute as @s[scores={CurrentRole=2}] run scoreboard players add 狂人 StartRoll 1
execute as @s[scores={CurrentRole=3}] run scoreboard players add 預言者 StartRoll 1
execute as @s[scores={CurrentRole=4}] run scoreboard players add 霊媒師 StartRoll 1
execute as @s[scores={CurrentRole=5}] run scoreboard players add 村人 StartRoll 1
execute as @s[scores={CurrentRole=6}] run scoreboard players add 怪盗 StartRoll 1
execute as @s[scores={CurrentRole=7}] run scoreboard players add 猫又 StartRoll 1
execute as @s[scores={CurrentRole=8}] run scoreboard players add 狐 StartRoll 1
execute as @s[scores={CurrentRole=9}] run scoreboard players add 狂信者 StartRoll 1
execute as @s[scores={CurrentRole=10}] run scoreboard players add 大狼 StartRoll 1
execute as @s[scores={CurrentRole=11}] run scoreboard players add 賢狼 StartRoll 1
execute as @s[scores={CurrentRole=12}] run scoreboard players add パン屋 StartRoll 1
execute as @s[scores={CurrentRole=13}] run scoreboard players add 囁く狂人 StartRoll 1
execute as @s[scores={CurrentRole=14}] run scoreboard players add 狼付き StartRoll 1
execute as @s[scores={CurrentRole=15}] run scoreboard players add 女王 StartRoll 1
execute as @s[scores={CurrentRole=16}] run scoreboard players add プリンセス StartRoll 1
execute as @s[scores={CurrentRole=17}] run scoreboard players add 狩人 StartRoll 1
execute as @s[scores={CurrentRole=18}] run scoreboard players add ボマー StartRoll 1
execute as @s[scores={CurrentRole=19}] run scoreboard players add 光の使徒 StartRoll 1
execute as @s[scores={CurrentRole=20}] run scoreboard players add 闇の化身 StartRoll 1